# Generated by Django 5.0.4 on 2024-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа'),
        ),
    ]
